// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {git} from '../models';
import {settings} from '../models';
import {filesystem} from '../models';

export function AddRecentProject(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CopyFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<terminal.SessionInfo>;

export function Delete(arg1:string):Promise<void>;

export function GetFileBase64(arg1:string):Promise<string>;

export function GetGitFileAtHead(arg1:string,arg2:string):Promise<string>;

export function GetGitStatus(arg1:string):Promise<git.Status>;

export function GetLSPStatus():Promise<Record<string, boolean>>;

export function GetRecentProjects():Promise<Array<settings.RecentProject>>;

export function GetSettings():Promise<settings.Settings>;

export function GetStartupPath():Promise<string>;

export function GetWorkspaceState():Promise<settings.WorkspaceState>;

export function InstallLSP(arg1:string):Promise<void>;

export function ListTerminals():Promise<Array<terminal.SessionInfo>>;

export function OpenFolderDialog():Promise<string>;

export function ReadDirectory(arg1:string,arg2:number):Promise<filesystem.FileNode>;

export function ReadDirectoryFlat(arg1:string):Promise<Array<filesystem.FileNode>>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RevealInOS(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SaveWorkspaceState(arg1:settings.WorkspaceState):Promise<void>;

export function SearchFiles(arg1:string,arg2:string,arg3:number):Promise<Array<filesystem.FileNode>>;

export function SearchTextContent(arg1:string,arg2:string,arg3:number):Promise<Array<filesystem.TextSearchResult>>;

export function SetHasUnsavedChanges(arg1:boolean):Promise<void>;

export function WatchWorkspace(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
