// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CopyFiles(arg1, arg2) {
  return window['go']['main']['App']['CopyFiles'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function GetFileBase64(arg1) {
  return window['go']['main']['App']['GetFileBase64'](arg1);
}

export function GetGitFileAtHead(arg1, arg2) {
  return window['go']['main']['App']['GetGitFileAtHead'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetLSPStatus() {
  return window['go']['main']['App']['GetLSPStatus']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStartupPath() {
  return window['go']['main']['App']['GetStartupPath']();
}

export function GetWorkspaceState() {
  return window['go']['main']['App']['GetWorkspaceState']();
}

export function InstallLSP(arg1) {
  return window['go']['main']['App']['InstallLSP'](arg1);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDirectory(arg1, arg2) {
  return window['go']['main']['App']['ReadDirectory'](arg1, arg2);
}

export function ReadDirectoryFlat(arg1) {
  return window['go']['main']['App']['ReadDirectoryFlat'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RevealInOS(arg1) {
  return window['go']['main']['App']['RevealInOS'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['main']['App']['SaveWorkspaceState'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SearchTextContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchTextContent'](arg1, arg2, arg3);
}

export function SetHasUnsavedChanges(arg1) {
  return window['go']['main']['App']['SetHasUnsavedChanges'](arg1);
}

export function WatchWorkspace(arg1) {
  return window['go']['main']['App']['WatchWorkspace'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
